[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tools.pytest.ini_options]
addopts = "--cov=Generalized-Rational-Variable-Projection-with-Application-in-ECG-Compression"
testpaths = [
    "tests",
]
